"""<br>
    @Author: Deven Gupta<br>
    @Date: 5-08-2024<br>
    @Last Modified by: Deven Gupta<br>
    @Last Modified time: 5-08-2024<br>
    @Title : Python programs on Numpy Library.<br>
"""<br>

In [1]:
import numpy as np

## 1.Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
Expected Output:<br>
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [2]:

def main():
    """
    Description :
        This function used to convert a list of numeric value into a one-dimensional NumPy array.
    Parameters :
        None
    return :
        None
    """
    lst = [12.23, 13.32, 100, 36.32]

    arr =np.array(lst)

    print(type(arr))
    print(f"The array of list is : {arr}")

if __name__ == "__main__":
    main()

<class 'numpy.ndarray'>
The array of list is : [ 12.23  13.32 100.    36.32]


## 2.Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]

In [3]:
def main():
    
    # arr =np.array([x for x in range(2,11)])
    arr =np.arange(2,11)

    arr=arr.reshape(3,3)

    print(f"Array after converting to 2d :\n {arr}")
    

if __name__ == "__main__":
    main()

Array after converting to 2d :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
