"""<br>
    @Author: Deven Gupta<br>
    @Date: 5-08-2024<br>
    @Last Modified by: Deven Gupta<br>
    @Last Modified time: 5-08-2024<br>
    @Title : Python programs on Numpy Library.<br>
"""<br>

In [1]:
import numpy as np

## 1.Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
Expected Output:<br>
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [2]:

def main():
    """
    Description :
        This function used to convert a list of numeric value into a one-dimensional NumPy array.
    Parameters :
        None
    return :
        None
    """
    lst = [12.23, 13.32, 100, 36.32]

    arr =np.array(lst)

    print(type(arr))
    print(f"The array of list is : {arr}")

if __name__ == "__main__":
    main()

<class 'numpy.ndarray'>
The array of list is : [ 12.23  13.32 100.    36.32]


## 2.Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]

In [3]:
def main():
    
    # arr =np.array([x for x in range(2,11)])
    arr =np.arange(2,11)

    arr=arr.reshape(3,3)

    print(f"Array after converting to 2d :\n {arr}")
    

if __name__ == "__main__":
    main()

Array after converting to 2d :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 3.Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]<br>
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [4]:
def main():

    #np.zeros((row,col))   #[[]]  null matrix
    arr =np.array([0 for i in range(10)],dtype='float')
    print(f"Before modification : {arr}")

    arr[5] = 11
    print(f"After Modification : {arr}")

    
if __name__ == "__main__":
    main()

Before modification : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After Modification : [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


## 4.Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [5]:
def reverse_array(arr):
    """
    Description :
        This function used to reverse an aaray
    Parameters :
        arr : input array 
    return :
        array : 1D reversed array
    """

    arr=np.flip(arr)
    
    # start=0
    # end =len(arr)-1
    # while start < end :
    #     arr[start],arr[end]=arr[end],arr[start]
    #     start += 1
    #     end -+ 1

    return arr

def main():
    arr = np.array([1,2,3,4,5,6,7,8])

    print(f"The original of array is {arr}")

    print(f"The reverse of array is {reverse_array(arr)}")


if __name__ == "__main__":
    main()

The original of array is [1 2 3 4 5 6 7 8]
The reverse of array is [8 7 6 5 4 3 2 1]


## 5.Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br>
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br>

In [6]:
def print_pattern(arr):
    """
    Description :
        This function used to create a 2d array with 1 on the border and 0 inside
    Parameters :
        arr : input array 
    return :
        array of 5x5(2D)
    """
    # arr[1:-1, 1:-1] = 0
     
    for row in range(len(arr)):
        for col in range(len(arr[0])):
            if row != 0 and row !=len(arr)-1 and col != 0 and col!=len(arr)-1 :
                arr[row,col]=0

    return arr


def main():
    arr = np.array([1 for num in range(25)])

    arr = arr.reshape(5,5)

    print(f"Before modification :\n{arr}\n")   
    print(f"After modification :\n{print_pattern(arr)}")


if __name__ == "__main__":
    main()

Before modification :
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

After modification :
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## 6.Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:<br>
Original array:<br>
[[ 1. 1. 1.]<br>
[ 1. 1. 1.]<br>
[ 1. 1. 1.]]<br>
1 on the border and 0 inside in the array<br>
[[ 0. 0. 0. 0. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 0. 0. 0. 0.]]

In [7]:
def pattern(arr):
    """
    Description :
        This function used to add border of zero (padding)
    Parameters :
        arr : input array 
    return :
        array of 5x5(2D)
    """

    # modified_aaray=np.pad(arr,pad_width=1,mode='constant',constant_values=0)

    modified_aaray = np.array([0 for _ in range(25)]).reshape(5,5)

    modified_aaray[1:-1,1:-1]=arr

    return modified_aaray

def main():
    arr = np.array([1 for num in range(9)])

    arr = arr.reshape(3,3)
    print(f"Before modification :\n{arr}\n")
    print(f"After modification :\n{pattern(arr)}")

    
if __name__ == "__main__":
    main()

Before modification :
[[1 1 1]
 [1 1 1]
 [1 1 1]]

After modification :
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


## 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:<br>
[[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]]


In [8]:
def main():
    arr = np.array([[(row + col) % 2 for col in range(8)]for row in range(8)])

    print(f"Checkboard Pattern : \n{arr}")

    
if __name__ == "__main__":
    main()

Checkboard Pattern : 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [9]:
def main():
    lst = [1,2,3,4,5,6,7,8]
    tup = (1,2,3,4,5,6,7,8)

    arr_list = np.array(lst)
    arr_tup = np.array(tup).reshape(2,4)

    print(f"List to array : {arr_list} \n Tuple to array : \n {arr_tup}")


if __name__ == "__main__":
    main()

List to array : [1 2 3 4 5 6 7 8] 
 Tuple to array : 
 [[1 2 3 4]
 [5 6 7 8]]


## 9.Write a Python program to append values to the end of an array.
Expected Output:<br>
Original array:<br>
[10, 20, 30]<br>
After append values to the end of the array:<br>
[10 20 30 40 50 60 70 80 90]


In [10]:
def main():
    arr =np.array([10,20,30])
    print(f"Original array : \n{arr}")

    arr = np.append(arr ,[40,50,60,70,80,90])

    print(f"After append values to the end of the array : \n{arr}")


if __name__ == "__main__":
    main()

Original array : 
[10 20 30]
After append values to the end of the array : 
[10 20 30 40 50 60 70 80 90]


## 10.Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]<br>
Real part of the array:<br>
[ 1. 0.70710678]<br>
Imaginary part of the array:<br>
[ 0. 0.70710678]


In [11]:
def main():

    arr =np.array([ 1+2j,4+3j])
    print(f"Real part : \n{arr.real}\nImaginary part :\n{arr.imag}")


if __name__ == "__main__":
    main()

Real part : 
[1. 4.]
Imaginary part :
[2. 3.]


## 11.Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.
Expected Output:<br>
Size of the array: 3<br>
Length of one array element in bytes: 8<br>
Total bytes consumed by the elements of the array: 24


In [12]:
def main():
    
      arr = np.array([1,2,3,4,5,6])

      size = arr.size
      size_of_element = arr.itemsize
      total_bytes = arr.nbytes            #size * size_of_element

      print(f"Size of array : {size}",
            f"\nLength of element in byte : {size_of_element}",
            f"\nTotal Bytes : {total_bytes}")


if __name__ == "__main__":
    main()

Size of array : 6 
Length of element in byte : 8 
Total Bytes : 48


## 12.Write a Python program to find common values between two arrays.
Expected Output:<br>
Array1: [ 0 10 20 40 60]<br>
Array2: [10, 30, 40]<br>
Common values between two arrays:<br>
[10 40]


In [13]:
def common_element(arr1,arr2):
    common_element=[]

    for element in arr1:
        if element in arr2:
            common_element.append(int(element))

    return common_element

def main():
    arr1 = np.array([0,10,20,40,60])
    arr2 = np.array([10,30,40])

    print(f"Common Elements are {common_element(arr1,arr2)}")


if __name__ == "__main__":
    main()

Common Elements are [10, 40]


## 13.Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
Expected Output:<br>
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70, 90]<br>
Set difference between two arrays:<br>
[ 0 20 60 80]


In [15]:
def set_diff(arr1,arr2):
    """
    Description :
        This function used to find the set differences of arrays
    Parameters :
        arr1 : 1st input array 
        arr2 : 2nd input array 
    return :
        list 
    """

    # set_difference = np.setdiff1d(arr1,arr2)

    set_difference = []
    for element in arr1:
        if element not in arr2:
            set_difference.append(int(element))

    return set_difference

def main():

    arr1 =np.array([0, 10, 20, 40, 60, 80])
    arr2 =np.array([10, 30, 40, 50, 70, 90])

    print(f"The set difference is : {set_diff(arr1,arr2)}")


if __name__ == "__main__":
    main()

The set difference is : [0, 20, 60, 80]


## 14.Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70]<br>
Unique values that are in only one (not both) of the input arrays:<br>
[ 0 20 30 50 60 70 80]

In [18]:
def set_xor(arr1,arr2):
    """
    Description :
        This function used to find the set exclusive-or of arrays
    Parameters :
        arr1 : 1st input array 
        arr2 : 2nd input array 
    return :
        array
    """

    set_xor = np.setxor1d(arr1,arr2)

    return set_xor

def main():

    arr1 =np.array([0, 10, 20, 40, 60, 80])
    arr2 =np.array([10, 30, 40, 50, 70, 90])

    print(f"The Set XOR of arrays is : {set_xor(arr1,arr2)}")


if __name__ == "__main__":
    main()

The Set XOR of arrays is : [ 0 20 30 50 60 70 80 90]


## 15.Write a Python program compare two arrays using numpy.
Array a: [1 2]<br>
Array b: [4 5]<br>
a > b<br>
[False False]<br>
a >= b<br>
[False False]<br>
a < b<br>
[ True True]<br>
a <= b<br>
[ True True]


In [20]:
def main():
    arr1 =np.array([1,2])
    arr2 =np.array([3,4])

    print(f"a>b : {arr1 > arr2}")
    print(f"a>=b : {arr1 >= arr2}")
    print(f"a<b : {arr1 < arr2}")
    print(f"a<=b : {arr1 <= arr2}")


if __name__ == "__main__":
    main()

a>b : [False False]
a>=b : [False False]
a<b : [ True  True]
a<=b : [ True  True]


## 16.Write a Python program to save a NumPy array to a text file.

In [21]:
def main():
    arr =np.array([1,2,3,4,5,602])

    np.savetxt("arr.txt",arr)

if __name__ == "__main__":
    main()

## 17.Write a Python program to create a contiguous flattened array.
Original array:<br>
[[10 20 30]<br>
[20 40 50]]<br>
New flattened array:<br>
[10 20 30 20 40 50]

In [22]:
def main():

    arr = np.array([[10,20,30],[20,40,50]])
    newarr = np.ravel(arr)

    print(f"New flattened array : {newarr}")


if __name__ == "__main__":
    main()

New flattened array : [10 20 30 20 40 50]


## 18.Write a Python program to change the data type of an array.
Expected Output:<br>
[[ 2 4 6]<br>
[ 6 8 10]]<br>
Data type of the array x is: int32<br>
New Type: float64<br>
[[ 2. 4. 6.]<br>
[ 6. 8. 10.]]

In [23]:
def main():
    arr = np.array([[2,4,6],[6,8,10]])

    print(f"The array is \n{arr}")
    print(f"\nThe original datatype of array is {arr.dtype}")


    newarr = arr.astype('float')
    print(f"\nThe new array after changing datatype is \n{newarr}")
    print(f"\nThe datatype of array is {newarr.dtype}")



if __name__ == "__main__":
    main()

The array is 
[[ 2  4  6]
 [ 6  8 10]]

The original datatype of array is int64

The new array after changing datatype is 
[[ 2.  4.  6.]
 [ 6.  8. 10.]]

The datatype of array is float64


## 19.Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.
Expected Output:<br>
[[ 1. 0. 0.]<br>
[ 0. 1. 0.]<br>
[ 0. 0. 1.]]


In [24]:
def main():
    arr =np.identity(3)

    print(f"The Array is : \n{arr}")

if __name__ == "__main__":
    main()

The Array is : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 20.Write a Python program to create an array which looks like below array.
Expected Output:<br>
[[ 0. 0. 0.]<br>
[ 1. 0. 0.]<br>
[ 1. 1. 0.]<br>
[ 1. 1. 1.]]

In [26]:
def main():
    arr = np.zeros((4, 3), dtype=int)
    
    # new = np.tril(arr)

    for i in range(4):
        for j in range(i):
            arr[i, j] = 1

    print("output pattern :\n",arr)


if __name__ == "__main__":
    main()

output pattern :
 [[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


## 21. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:<br>
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]])<br>
Expected Output:<br>
[[ 0 1 3 0 2 4]<br>
[ 5 7 9 6 8 10]]

In [27]:
def main():
    
    arr1 = np.array([[0, 1, 3], [5, 7, 9]])
    arr2 = np.array([[0, 2, 4], [6, 8, 10]])

    newarr= np.concatenate((arr1,arr2),axis=1)

    print(f"Concatenated array is : \n{newarr}")


if __name__ == "__main__":
    main()

Concatenated array is : 
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


## 22.Write a Python program to make an array immutable (read-only).
Expected Output:<br>
Test the array is read-only or not:<br>
Try to change the value of the first element:<br>
Traceback (most recent call last):<br>
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in<br>
x[0] = 1<br>
ValueError: assignment destination is read-only

In [28]:
def main():

    arr =np.array([1,2,3,4,5])
    print(arr)

    arr.flags.writeable=False
    arr[0]=1

if __name__ == "__main__":
    main()


[1 2 3 4 5]


ValueError: assignment destination is read-only

## 23.Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.
Expected Output:<br>
Original array elements:<br>
[[ 0 1 2 3]<br>
[ 4 5 6 7]<br>
[ 8 9 10 11]]<br>
New array elements:<br>
[[ 0 3 6 9]<br>
[12 15 18 21]<br>
[24 27 30 33]]

In [29]:
def main():
    arr = np.arange(12).reshape(3,4)

    print(f"The Array is : \n {arr}")

    newarr = arr * 3

    print(f"\nArray after multiplication : \n {newarr}")


if __name__ == "__main__":
    main()

The Array is : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array after multiplication : 
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


## 24.Write a Python program to convert a NumPy array into Python list structure.
Expected Output:<br>
Original array elements:<br>
[[0 1]<br>
[2 3]<br>
[4 5]]<br>
Array to list:<br>
[[0, 1], [2, 3], [4, 5]]

In [30]:
def main():
    arr = np.arange(6).reshape(3,2)

    print(f"The Array is : \n {arr}")

    # arrlist = list(arr)

    arrlist = arr.tolist()
    

    print(f"\nArray after converting to list : \n {arrlist}")


if __name__ == "__main__":
    main()

The Array is : 
 [[0 1]
 [2 3]
 [4 5]]

Array after converting to list : 
 [[0, 1], [2, 3], [4, 5]]


## 25.Write a Python program to convert a NumPy array into Python list structure.
Expected Output:<br>
Original array elements:<br>
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349<br>
0.35399976 0.99469633 0.0694458 0.54711478]<br>
Print array values with precision 3:<br>
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [31]:
def main():
    arr = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
                    0.35399976,0.99469633,0.0694458,0.54711478])

    print(f"The Array is : \n {arr}")
 
    np.set_printoptions(precision=3)

    print(f"\nArray after setting precision : \n {arr}")


if __name__ == "__main__":
    main()

The Array is : 
 [0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]

Array after setting precision : 
 [0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]
