"""<br>
    @Author: Deven Gupta<br>
    @Date: 5-08-2024<br>
    @Last Modified by: Deven Gupta<br>
    @Last Modified time: 5-08-2024<br>
    @Title : Python programs on Numpy Library.<br>
"""<br>

In [1]:
import numpy as np

## 1.Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
Expected Output:<br>
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [2]:

def main():
    """
    Description :
        This function used to convert a list of numeric value into a one-dimensional NumPy array.
    Parameters :
        None
    return :
        None
    """
    lst = [12.23, 13.32, 100, 36.32]

    arr =np.array(lst)

    print(type(arr))
    print(f"The array of list is : {arr}")

if __name__ == "__main__":
    main()

<class 'numpy.ndarray'>
The array of list is : [ 12.23  13.32 100.    36.32]


## 2.Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]

In [3]:
def main():
    
    # arr =np.array([x for x in range(2,11)])
    arr =np.arange(2,11)

    arr=arr.reshape(3,3)

    print(f"Array after converting to 2d :\n {arr}")
    

if __name__ == "__main__":
    main()

Array after converting to 2d :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 3.Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]<br>
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [4]:
def main():

    #np.zeros((row,col))   #[[]]  null matrix
    arr =np.array([0 for i in range(10)],dtype='float')
    print(f"Before modification : {arr}")

    arr[5] = 11
    print(f"After Modification : {arr}")

    
if __name__ == "__main__":
    main()

Before modification : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After Modification : [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


## 4.Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [5]:
def reverse_array(arr):
    """
    Description :
        This function used to reverse an aaray
    Parameters :
        arr : input array 
    return :
        array : 1D reversed array
    """

    arr=np.flip(arr)
    
    # start=0
    # end =len(arr)-1
    # while start < end :
    #     arr[start],arr[end]=arr[end],arr[start]
    #     start += 1
    #     end -+ 1

    return arr

def main():
    arr = np.array([1,2,3,4,5,6,7,8])

    print(f"The original of array is {arr}")

    print(f"The reverse of array is {reverse_array(arr)}")


if __name__ == "__main__":
    main()

The original of array is [1 2 3 4 5 6 7 8]
The reverse of array is [8 7 6 5 4 3 2 1]


## 5.Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br>
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br>

In [6]:
def print_pattern(arr):
    """
    Description :
        This function used to create a 2d array with 1 on the border and 0 inside
    Parameters :
        arr : input array 
    return :
        array of 5x5(2D)
    """
    # arr[1:-1, 1:-1] = 0
     
    for row in range(len(arr)):
        for col in range(len(arr[0])):
            if row != 0 and row !=len(arr)-1 and col != 0 and col!=len(arr)-1 :
                arr[row,col]=0

    return arr


def main():
    arr = np.array([1 for num in range(25)])

    arr = arr.reshape(5,5)

    print(f"Before modification :\n{arr}\n")   
    print(f"After modification :\n{print_pattern(arr)}")


if __name__ == "__main__":
    main()

Before modification :
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

After modification :
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## 6.Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:<br>
Original array:<br>
[[ 1. 1. 1.]<br>
[ 1. 1. 1.]<br>
[ 1. 1. 1.]]<br>
1 on the border and 0 inside in the array<br>
[[ 0. 0. 0. 0. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 0. 0. 0. 0.]]

In [7]:
def pattern(arr):
    """
    Description :
        This function used to add border of zero (padding)
    Parameters :
        arr : input array 
    return :
        array of 5x5(2D)
    """

    # modified_aaray=np.pad(arr,pad_width=1,mode='constant',constant_values=0)

    modified_aaray = np.array([0 for _ in range(25)]).reshape(5,5)

    modified_aaray[1:-1,1:-1]=arr

    return modified_aaray

def main():
    arr = np.array([1 for num in range(9)])

    arr = arr.reshape(3,3)
    print(f"Before modification :\n{arr}\n")
    print(f"After modification :\n{pattern(arr)}")

    
if __name__ == "__main__":
    main()

Before modification :
[[1 1 1]
 [1 1 1]
 [1 1 1]]

After modification :
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


## 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:<br>
[[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]]


In [8]:
def main():
    arr = np.array([[(row + col) % 2 for col in range(8)]for row in range(8)])

    print(f"Checkboard Pattern : \n{arr}")

    
if __name__ == "__main__":
    main()

Checkboard Pattern : 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [9]:
def main():
    lst = [1,2,3,4,5,6,7,8]
    tup = (1,2,3,4,5,6,7,8)

    arr_list = np.array(lst)
    arr_tup = np.array(tup).reshape(2,4)

    print(f"List to array : {arr_list} \n Tuple to array : \n {arr_tup}")


if __name__ == "__main__":
    main()

List to array : [1 2 3 4 5 6 7 8] 
 Tuple to array : 
 [[1 2 3 4]
 [5 6 7 8]]
