"""<br>
    @Author: Deven Gupta<br>
    @Date: 7-08-2024<br>
    @Last Modified by: Deven Gupta<br>
    @Last Modified time: 7-08-2024<br>
    @Title : Python programs on Numpy Library.<br>
"""<br>

In [1]:
import numpy as np
import pandas as pd

## 1.Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [2]:
def main():
    arr = np.arange(5)
    print(arr)


    ds = pd.Series(arr)
    print(ds)


if __name__ == "__main__":
    main()

[0 1 2 3 4]
0    0
1    1
2    2
3    3
4    4
dtype: int64


## 2.Write a Python program to convert a Panda module Series to Python list and it's type

In [3]:
def main():
    dic ={1:'Deven',
          2:'Prayag',
          3:'Shivraj',
          4:'Ayush'}
    print(f"\nThe Original Dictionary is {dic}")
    print(type(dic))


    ds = pd.Series(dic)
    print(f"\nThe Panda module Series is \n{ds}")
    print(type(ds))
    

    lst=ds.tolist()
    print(f"\nThe List of Series is {lst}")
    print(type(lst))


if __name__ == "__main__":
    main()


The Original Dictionary is {1: 'Deven', 2: 'Prayag', 3: 'Shivraj', 4: 'Ayush'}
<class 'dict'>

The Panda module Series is 
1      Deven
2     Prayag
3    Shivraj
4      Ayush
dtype: object
<class 'pandas.core.series.Series'>

The List of Series is ['Deven', 'Prayag', 'Shivraj', 'Ayush']
<class 'list'>


## 3. Write a Python program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [4]:
def series_operation(s1,s2):
    """
        Description :
            This function is used to perform operation on series
        Parameters :
            s1: First series
            s2: Second series
        return :
            tuple : contain addition ,subtraction ,multiplication ,division
     """


    # addition = s1.add(s2)
    # subtraction = s1.sub(s2)
    # multiplication = s1.mul(s2)
    # division = s1.div(s2)

    add = s1 + s2
    sub = s1 - s2
    mul = s1 * s2
    div = s1 / s2

    return add,sub,mul,div

def main():
    series1 = pd.Series([2, 4, 6, 8, 10])
    series2 = pd.Series([1, 3, 5, 7, 9])


    addition,subtraction,multiplication,division = series_operation(series1,series2)

    print(f"\nAddition of series is \n {addition}")
    print(f"\nSubtraction of series is \n {subtraction}")
    print(f"\nMultiplication of series is \n {multiplication}")
    print(f"\nDivision of series is \n {division}")



if __name__ == "__main__":
    main()



Addition of series is 
 0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtraction of series is 
 0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiplication of series is 
 0     2
1    12
2    30
3    56
4    90
dtype: int64

Division of series is 
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


## 4. Write a Python program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array<br>
Expected Output:<br>
Original array<br>
[0 1 2 3 4 5 6]<br>
First array elements raised to powers from second array, element-wise:<br>
[ 0 1 8 27 64 125 216]

In [3]:
def main():
    series1 = pd.Series([0,1,2,3,4,5,6])
    series2 = pd.Series([3,3,3,3,3,3,3])


    result_array = np.power(series1,series2).tolist()

    # lst = np.array([(series1[i]**series2[i])for i in range(len(series1))])
    # print(lst)


    print(result_array)


if __name__ == "__main__":
    main()

[0, 1, 8, 27, 64, 125, 216]


## 5. Write a Python program to create and display a DataFrame from a specified dictionary data which has the index labels.
Sample Python dictionary data and list labels:<br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',<br>
'Matthew', 'Laura', 'Kevin', 'Jonas'],<br>
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],<br>
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],<br>
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}<br>
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']<br>

In [4]:
def main():
    exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
                'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
              'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
    
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

    df = pd.DataFrame(exam_data,index=labels)

    print(df)

if __name__ == "__main__":
    main()

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


## 6. Write a Python program to display a summary of the basic information about a specified Data Frame and its data.
Sample Python dictionary data and list labels:<br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',<br>
'Laura', 'Kevin', 'Jonas'],<br>
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],<br>
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],<br>
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}<br>
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [4]:
def main():
    exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
                'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
              'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
    
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

    df = pd.DataFrame(exam_data,index=labels)

    df.info()

if __name__ == "__main__":
    main()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


## 7. Write a Python program to get the first 3 rows of a given DataFrame.
Sample Python dictionary data and list labels:<br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',<br>
'Laura', 'Kevin', 'Jonas'],<br>
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],<br>
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],<br>
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}<br>
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [6]:
def main():
    exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
                'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
              'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
    
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

    df = pd.DataFrame(exam_data,index=labels)

    print(df.head(3))

if __name__ == "__main__":
    main()

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
